### ISSUE TITLE
博客页面总是会显示水平滚动条

### ISSUE THREAD

**Issue by pengx17** [codepiano/codepiano.github.com#1]
经过调整，我发现是导航条的左右border导致的，设置成0后问题消失。

文件[css/codepiano.css](https://github.com/codepiano/codepiano.github.com/blob/master/css/codepiano.css)84行改成：

``` css
.navbar>.navbar-inner{
  padding-left: 0px;
  padding-right: 0px;
  border-left: none;
  border-right: none;
}
```
